### ISSUE TITLE
Getting strange numbers for temperature

### ISSUE THREAD

**Issue by kamenomagic** [ralscha/darksky#1]
```
darksky.sendForecastRequest(DsForecastRequest.builder()
            .latitude(latitude).longitude(longitude)
            .excludeBlock(DsBlock.ALERTS, DsBlock.MINUTELY, DsBlock.HOURLY)
            .unit(DsUnit.SI).build()
).currently().temperature()

```
I also try apparentTemperature, but for both I get values of about 5/6 degrees, but the API itself gives about 40 degrees for the same latitude and longitude. Is it just me?

**Comment by ralscha** [comment]
Hi
Looks like a bug. I will look into it.

**Comment by kamenomagic** [comment]
Thanks. I tried to look at the code myself a bit but couldn't quite figure it out. Let me know if I can help or give more info

**Comment by ralscha** [comment]
It looks okay to me

```
 DsClient client = new DsClient("...api key...");
    DsDataPoint currently = client.sendForecastRequest(
        DsForecastRequest.builder().latitude("40.7127").longitude("-74.0059")
            .excludeBlock(DsBlock.ALERTS, DsBlock.MINUTELY, DsBlock.HOURLY)
            .unit(DsUnit.SI).build())
        .currently();
    
    BigDecimal bd = currently.temperature();
    System.out.println(bd);
```

This code prints 15.91 and when I check the raw data with this link I see the same value in the currently block
```
https://api.darksky.net/forecast/...api_key..../40.7127,-74.0059?units=si
```

```
{"latitude":40.7127,"longitude":-74.0059,"timezone":"America/New_York",
"currently":
   {"time":1509952256,"summary":"Mostly Cloudy","icon":"partly-cloudy-
     night","nearestStormDistance":53,"nearestStormBearing":296,
     "precipIntensity":0,"precipProbability":0,
    "temperature":15.91,
.....
```

**Comment by ralscha** [comment]
Maybe Celsius / Fahrenheit?
5/6 Celsius is about 33 Fahrenheit.

**Comment by kamenomagic** [comment]
Hmm that's smart, that's likely what's happening here, but I have no idea why the raw API response would be in fahrenheit and this code return me celsius. I'm not setting any flags anywhere to change them. I'm fine doing a conversion, but I wonder what's going on there

**Comment by ralscha** [comment]
You are setting a flag.  The `.unit(DsUnit.SI)` code selects the International System of Units (SI). 
Which returns the temperatures in Celsius.

If you are calling the API without any flags you get Fahrenheit by default:
https://api.darksky.net/forecast/...api_key..../40.7127,-74.0059

If you need Fahrenheit you have to remove the `.unit(DsUnit.SI)` code.

**Comment by kamenomagic** [comment]
Oh nope, that's exactly what I was doing. I just saw that right when you commented. Thanks so much for your response and help!

**Comment by ralscha** [comment]
No problem. Glad I could help
