### ISSUE TITLE
How do you use the TimeMachineRequest?

### ISSUE THREAD

**Issue by Dragonflares** [ralscha/darksky#2]
```
public class DarkSkyAPI {
	public final float darTemperaturaActual(int day) throws IOException
	{
		DsClient client = new DsClient("9ee9579e309df4f7c0806b5e60b90e71");
		DsTimeMachineRequest request = DsTimeMachineRequest.builder()
		        .latitude("-34.6157437")
				.longitude("-58.5733854")				
				.unit(DsUnit.SI)
				.time(ZonedDateTime.now().minusDays(-day).toEpochSecond())
				.build();
		DsResponse response = client.sendTimeMachineRequest(request);
		for (DsDataPoint dataPoint : response.hourly().data()) {			
		    ZoneId zoneId = ZoneId.of(response.timezone());
		    Instant instant = Instant.ofEpochSecond(dataPoint.time());
		    ZonedDateTime time = ZonedDateTime.ofInstant(instant, zoneId);

		    System.out.print(time);
		    System.out.print(": ");
		    System.out.println(dataPoint);            
		}
		float temp = 0;
		return temp;
	}
}
```

So I'm doing this for something we need at our University, and I'm kinda confused onto how to process the response in your API, as we need the temperature from a date 16 or 10 days in the future. Any advice on how to do this?

Thanks

**Comment by ralscha** [comment]
Hi

`response.hourly()` returns 24 data points, one for each hour of the requested day.

If you are only interested in one data point you can call the method `response.currently()` instead
This method returns the data point for the request date and time

Then you have access to the temperate and the apparent (or “feels like”) temperature
```
DsDataPoint dataPoint = response.currently();
ZoneId zoneId = ZoneId.of(response.timezone());
Instant instant = Instant.ofEpochSecond(dataPoint.time());
ZonedDateTime time = ZonedDateTime.ofInstant(instant, zoneId);
System.out.print(time);
System.out.print(": ");
System.out.println(dataPoint);
		
System.out.println(dataPoint.temperature());
System.out.println(dataPoint.apparentTemperature());
```

I also recommend limiting the response by calling `includeBlock`. If your application is only interested in the currently response call: `.includeBlock(DsBlock.CURRENTLY)`
This reduces the size of the JSON response that DarkSky sends to your client.
```
DsTimeMachineRequest request = DsTimeMachineRequest.builder()
		.latitude("-34.6157437").longitude("-58.5733854")
		.includeBlock(DsBlock.CURRENTLY)
		.unit(DsUnit.SI)
		.time(ZonedDateTime.now().plusDays(day).toEpochSecond()).build();
```

**Comment by Dragonflares** [comment]
Oh nice! Thanks!

Just 2 more questions.

A) Is using negative numbers as a parameter for ZonedDateTime.now().minusDays("-day") gonna end up giving me the date I expect in the near future? 
B) How far can this API forecast the weather towards the future as a max? 15 days?

Thanks for the previous explanation! I'm quite new to Java and it's a bit hard to understand sometimes

**Comment by ralscha** [comment]
A) Yes that works. It's the same as `ZonedDateTime.now().plusDays(day)`. 

B) That's a good question, unfortunately I don't have an answer. I don't see any information about this in the documentation. https://darksky.net/dev/docs
Maybe it depends on the region

C) Here an example that returns the hourly temperatures for one day in the future. The method returns an array with 24 elements. First element represent 00:00 of the day and the last element is 23:00

```
	public static void main(String[] args) throws IOException {
		double[] temps = darTemperaturaActual(10); 
		
		for (int i = 0; i < temps.length; i++) {
			System.out.print(i + ":00 -> ");
			System.out.println(temps[i]);
		}
	}
	
	public static double[] darTemperaturaActual(int day) throws IOException {
		DsClient client = new DsClient("9ee9579e309df4f7c0806b5e60b90e71");
		DsTimeMachineRequest request = DsTimeMachineRequest.builder()
				.includeBlock(DsBlock.HOURLY)
				.latitude("-34.6157437").longitude("-58.5733854").unit(DsUnit.SI)
				.time(ZonedDateTime.now().plusDays(day).toEpochSecond()).build();

		double[] result = new double[24];
		int ix = 0;
		DsResponse response = client.sendTimeMachineRequest(request);
		for (DsDataPoint dataPoint : response.hourly().data()) {
			ZoneId zoneId = ZoneId.of(response.timezone());
			Instant instant = Instant.ofEpochSecond(dataPoint.time());
			ZonedDateTime time = ZonedDateTime.ofInstant(instant, zoneId);

			System.out.print(time);
			System.out.print(": ");
			System.out.println(dataPoint);

			result[ix++] = dataPoint.temperature().doubleValue();
		}
		return result;
	}
```

**Comment by ralscha** [comment]
For completeness sake here the example with `currently()`. This returns the forecast for the currentDay + day and the current time. If you run this on August 5th at 10pm you get the forecast for August 15th at 10pm

```
	public static void main(String[] args) throws IOException {
		double temp = darTemperaturaActual(10);
		System.out.println(temp);
	}

	public static double darTemperaturaActual(int day) throws IOException {
		DsClient client = new DsClient("9ee9579e309df4f7c0806b5e60b90e71");
		DsTimeMachineRequest request = DsTimeMachineRequest.builder()
				.includeBlock(DsBlock.CURRENTLY).latitude("-34.6157437")
				.longitude("-58.5733854").unit(DsUnit.SI)
				.time(ZonedDateTime.now().plusDays(day).toEpochSecond()).build();

		DsResponse response = client.sendTimeMachineRequest(request);
		DsDataPoint dataPoint = response.currently();

		ZoneId zoneId = ZoneId.of(response.timezone());
		Instant instant = Instant.ofEpochSecond(dataPoint.time());
		ZonedDateTime time = ZonedDateTime.ofInstant(instant, zoneId);

		System.out.print(time);
		System.out.print(": ");
		System.out.println(dataPoint);

		return dataPoint.temperature().doubleValue();
	}
```

**Comment by Dragonflares** [comment]
That's great! It's just what I needed, thank you

I have one last request involving this topic and it will be all:

If I needed to get the weather conditions like: sunny, drizzle, rain, etc, which call would I need?

**Comment by ralscha** [comment]
`dataPoint.icon()` returns weather conditions: 

> A machine-readable text summary of this data point, suitable for selecting an icon for display. If defined, this property will have one of the following values: clear-day, clear-night, rain, snow, sleet, wind, fog, cloudy, partly-cloudy-day, or partly-cloudy-night. (Developers should ensure that a sensible default is defined, as additional values, such as hail, thunderstorm, or tornado, may be defined in the future.)

`dataPoint.summary()` might also be interesting. It's a human readable text

> A human-readable text summary of this data point. (This property has millions of possible values, so don’t use it for automated purposes: use the icon property, instead!)

You find the documentation of all the fields here:    
https://darksky.net/dev/docs

**Comment by Dragonflares** [comment]
Thank you @ralscha I'll be using this in my code, thanks a lot for all the help! Closing the issue now
